### ISSUE TITLE
nyx support

### ISSUE THREAD

**Issue by ehnwebmaster** [klemmchr/tor-alpine#6]
Hello what about adding nyx support for statistics?

https://nyx.torproject.org/

```
RUN apk add --update \
     python \
     python-dev \
     py-pip \
     build-base \
  && pip install nyx
```

Also will need 

`ControlPort 9051`

and  authentication method of course

And maybe add localtime?

`-v /etc/localtime:/etc/localtime \`

And add environment:

`-e 'NICKNAME=ehn' \`

**Comment by klemmchr** [comment]
This is supposed to be a lightweight package. Therefore I have no plans on including any third party dependencies to it. This is especially true when Python is needed.

> And maybe add localtime?
> -v /etc/localtime:/etc/localtime \
> And add environment:
> -e 'NICKNAME=ehn' \

I don't understand what you mean.
